# Generated by Django 6.1 on 2026-08-28 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_tenant_is_wati_enabled_tenant_wati_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceHeatmap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("count", models.PositiveIntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "analytics_attendance_heatmap",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "date"), name="uq_analytics_heatmap_tenant_date")
                ],
            },
        ),
        migrations.CreateModel(
            name="MembershipFunnel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "analytics_membership_funnel",
                "ordering": ["stage"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "stage"), name="uq_analytics_funnel_tenant_stage")
                ],
            },
        ),
        migrations.CreateModel(
            name="RevenueReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period", models.DateField(db_index=True)),
                ("amount", models.BigIntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "analytics_revenue_report",
                "ordering": ["-period"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "period"), name="uq_analytics_revenue_tenant_period")
                ],
            },
        ),
        migrations.CreateModel(
            name="TopCustomer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_id", models.BigIntegerField(db_index=True)),
                ("total_spent", models.BigIntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "analytics_top_customer",
                "ordering": ["-total_spent"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "customer_id"), name="uq_analytics_topcustomer_tenant_customer"
                    )
                ],
            },
        ),
    ]
