# Generated by Django 6.1 on 2026-08-24 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_extensions"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "goal",
                    models.CharField(
                        choices=[("bulk", "Bulk"), ("cut", "Cut"), ("maintain", "Maintain")],
                        default="maintain",
                        max_length=20,
                    ),
                ),
                ("daily_calories", models.PositiveIntegerField(default=0)),
                ("protein_ratio", models.FloatField(default=30.0, help_text="Target protein share of calories (%).")),
                ("carb_ratio", models.FloatField(default=40.0, help_text="Target carb share of calories (%).")),
                ("fat_ratio", models.FloatField(default=30.0, help_text="Target fat share of calories (%).")),
                ("duration_days", models.PositiveIntegerField(default=7)),
                (
                    "is_template",
                    models.BooleanField(
                        default=False, help_text="Template plans can be duplicated to create new plans."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "diet_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DietDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_number", models.PositiveIntegerField()),
                (
                    "total_calories",
                    models.PositiveIntegerField(
                        default=0, help_text="Auto-calculated sum of meal calories for the day."
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "diet_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="days", to="diet.dietplan"
                    ),
                ),
            ],
            options={
                "db_table": "diet_days",
                "ordering": ["diet_plan", "day_number"],
            },
        ),
        migrations.CreateModel(
            name="DietAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(default=django.utils.timezone.localdate)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diet_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_assignments",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "diet_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="diet.dietplan"
                    ),
                ),
            ],
            options={
                "db_table": "diet_assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                (
                    "serving_size",
                    models.CharField(
                        default="100g",
                        help_text="Serving size the nutrition values refer to, e.g. '100g', '1 cup', '1 medium'.",
                        max_length=100,
                    ),
                ),
                ("calories", models.FloatField(default=0, help_text="Calories (kcal) per serving size.")),
                ("protein", models.FloatField(default=0, help_text="Protein (g) per serving size.")),
                ("carbs", models.FloatField(default=0, help_text="Carbohydrates (g) per serving size.")),
                ("fat", models.FloatField(default=0, help_text="Fat (g) per serving size.")),
                ("fiber", models.FloatField(default=0, help_text="Dietary fiber (g) per serving size.")),
                ("glycemic_index", models.IntegerField(blank=True, help_text="Glycemic index (optional).", null=True)),
                (
                    "food_group",
                    models.CharField(
                        choices=[
                            ("grains", "Grains"),
                            ("protein", "Protein"),
                            ("vegetable", "Vegetable"),
                            ("fruit", "Fruit"),
                            ("dairy", "Dairy"),
                            ("fat", "Fat"),
                            ("snack", "Snack"),
                            ("beverage", "Beverage"),
                        ],
                        default="grains",
                        max_length=20,
                    ),
                ),
                ("is_veg", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "diet_food_items",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["food_group"], name="diet_food_i_food_gr_23803c_idx"),
                    models.Index(fields=["is_veg"], name="diet_food_i_is_veg_7a9bef_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DietMeal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("morning_snack", "Morning Snack"),
                            ("lunch", "Lunch"),
                            ("evening_snack", "Evening Snack"),
                            ("dinner", "Dinner"),
                        ],
                        default="breakfast",
                        max_length=20,
                    ),
                ),
                ("quantity", models.FloatField(default=1.0, help_text="Multiplier of the food item's serving size.")),
                (
                    "calories",
                    models.FloatField(default=0, help_text="Auto-calculated = food_item.calories × quantity."),
                ),
                ("protein", models.FloatField(default=0, help_text="Auto-calculated = food_item.protein × quantity.")),
                ("carbs", models.FloatField(default=0, help_text="Auto-calculated = food_item.carbs × quantity.")),
                ("fat", models.FloatField(default=0, help_text="Auto-calculated = food_item.fat × quantity.")),
                (
                    "diet_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="meals", to="diet.dietday"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="diet_meals", to="diet.fooditem"
                    ),
                ),
            ],
            options={
                "db_table": "diet_meals",
                "ordering": ["diet_day", "meal_type", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="dietday",
            constraint=models.UniqueConstraint(fields=("diet_plan", "day_number"), name="uq_diet_day_plan_number"),
        ),
    ]
