# Generated by Django 6.1 on 2026-09-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietmeal",
            name="is_completed",
            field=models.BooleanField(default=False, help_text="Whether the customer has logged this meal as eaten."),
        ),
    ]
