# Generated by Django 6.1 on 2026-08-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0002_initial"),
        ("customers", "0002_customer_extensions"),
        ("tenants", "0001_initial"),
        ("users", "0003_remove_membership_customer_remove_membership_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("check_in_time", models.DateTimeField()),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[("qr", "QR Code"), ("mobile", "Mobile"), ("manual", "Manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="branches.branch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "attendance_records",
                "ordering": ["-check_in_time", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "customer", "date"], name="idx_att_customer_date"),
                    models.Index(fields=["tenant", "branch", "date"], name="idx_att_branch_date"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrainerAttendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("check_in_time", models.DateTimeField()),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainer_attendance",
                        to="branches.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="users.trainer",
                    ),
                ),
            ],
            options={
                "db_table": "trainer_attendance",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["tenant", "trainer", "date"], name="idx_trainer_date")],
            },
        ),
    ]
