# Generated by Django 6.1 on 2026-09-06 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("branches", "0002_initial"),
        ("tenants", "0002_tenant_is_wati_enabled_tenant_wati_api_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[("present", "Present"), ("late", "Late"), ("absent", "Absent"), ("left", "Left")],
                default="present",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trainerattendance",
            name="status",
            field=models.CharField(
                choices=[("present", "Present"), ("late", "Late"), ("absent", "Absent"), ("left", "Left")],
                default="present",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("check_in_time", models.DateTimeField()),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[("qr", "QR Code"), ("mobile", "Mobile"), ("manual", "Manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("late", "Late"), ("absent", "Absent"), ("left", "Left")],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_attendance",
                        to="branches.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "staff_attendance",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["tenant", "user", "date"], name="idx_staff_att_date")],
            },
        ),
    ]
