# Generated by Django 6.1 on 2026-08-23 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0002_initial"),
        ("customers", "0002_customer_extensions"),
        ("tenants", "0001_initial"),
        ("users", "0004_trainer_certifications_trainer_experience_years_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("unassigned_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainer_assignment_records",
                        to="branches.branch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_assignment_records",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="users.trainer"
                    ),
                ),
            ],
            options={
                "db_table": "trainer_assignments",
                "ordering": ["-assigned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "trainer", "customer"), name="uq_trainer_assignment_tenant_trainer_customer"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrainerPerformance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField(help_text="First day of the month the snapshot applies to.")),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Revenue attributed to the trainer in the month.",
                        max_digits=12,
                    ),
                ),
                (
                    "customer_count",
                    models.PositiveIntegerField(default=0, help_text="Number of active customers served in the month."),
                ),
                (
                    "rating_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average trainer rating for the month (0.00–5.00).",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "sessions_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of training sessions completed in the month."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to="users.trainer",
                    ),
                ),
            ],
            options={
                "db_table": "trainer_performance",
                "ordering": ["-month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "trainer", "month"), name="uq_trainer_performance_tenant_trainer_month"
                    )
                ],
            },
        ),
    ]
