# Generated by Django 6.1 on 2026-08-24 14:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diet", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIMealPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("target_calories", models.PositiveIntegerField(default=0)),
                ("target_protein_g", models.FloatField(default=0)),
                ("target_carbs_g", models.FloatField(default=0)),
                ("target_fat_g", models.FloatField(default=0)),
                ("cuisine_preference", models.CharField(blank=True, max_length=50)),
                (
                    "dietary_restrictions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON array of dietary restrictions, e.g. ['vegetarian', 'no-gluten'].",
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.localdate)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_meal_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_meal_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMealPlanItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                        help_text="0 = Monday ... 6 = Sunday.",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("snack", "Snack"),
                            ("dinner", "Dinner"),
                        ],
                        default="breakfast",
                        max_length=20,
                    ),
                ),
                ("servings", models.FloatField(default=1.0, help_text="Multiplier of the food item's serving size.")),
                (
                    "calories",
                    models.FloatField(default=0, help_text="Auto-calculated = food_item.calories × servings."),
                ),
                (
                    "protein_g",
                    models.FloatField(default=0, help_text="Auto-calculated = food_item.protein × servings."),
                ),
                ("carbs_g", models.FloatField(default=0, help_text="Auto-calculated = food_item.carbs × servings.")),
                ("fat_g", models.FloatField(default=0, help_text="Auto-calculated = food_item.fat × servings.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_meal_plan_items",
                        to="diet.fooditem",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="ai_nutrition.aimealplan"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "ai_meal_plan_items",
                "ordering": ["meal_plan", "day_of_week", "meal_type", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")], default="active", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_lists",
                        to="ai_nutrition.aimealplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_shopping_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_shopping_lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.FloatField(default=1.0)),
                ("unit", models.CharField(default="serving", max_length=50)),
                ("is_purchased", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_shopping_list_items",
                        to="diet.fooditem",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ai_nutrition.shoppinglist",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "ai_shopping_list_items",
                "ordering": ["shopping_list", "id"],
            },
        ),
        migrations.CreateModel(
            name="MacroLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("calories_consumed", models.FloatField(default=0)),
                ("protein_consumed_g", models.FloatField(default=0)),
                ("carbs_consumed_g", models.FloatField(default=0)),
                ("fat_consumed_g", models.FloatField(default=0)),
                ("water_intake_ml", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_macro_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_macro_logs",
                "ordering": ["-date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "user", "date"), name="uq_ai_macro_log_tenant_user_date")
                ],
            },
        ),
    ]
