# Generated by Django 6.1 on 2026-08-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.JSONField(blank=True, default=dict)),
                ("date", models.DateField(auto_now_add=True)),
                ("auto_updated", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_cache",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "metric_name", "date"), name="uq_dashboard_cache_tenant_metric_date"
                    )
                ],
            },
        ),
    ]
