# Generated by Django 6.1 on 2026-08-23 05:34

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="uq_user_tenant_email",
        ),
    ]
