# Generated by Django 6.1 on 2026-08-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_uq_user_tenant_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="plan",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
        migrations.DeleteModel(
            name="MembershipPlan",
        ),
    ]
