# Generated by Django 6.1 on 2026-08-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_extensions"),
        ("tenants", "0001_initial"),
        ("users", "0003_remove_membership_customer_remove_membership_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="certifications",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of {name, issuer, year, expiry} objects."
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainer",
            name="max_clients",
            field=models.PositiveIntegerField(default=50, help_text="Maximum simultaneous clients allowed."),
        ),
        migrations.AddField(
            model_name="trainer",
            name="profile_photo",
            field=models.URLField(blank=True, help_text="URL to the trainer's profile photo."),
        ),
        migrations.AddField(
            model_name="trainer",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Average rating (0.00–5.00).", max_digits=3
            ),
        ),
        migrations.CreateModel(
            name="TrainerCustomerAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("unassigned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_assignments",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_assignments",
                        to="users.trainer",
                    ),
                ),
            ],
            options={
                "db_table": "trainer_customer_assignments",
                "ordering": ["-assigned_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("trainer", "customer"), name="uq_trainer_customer_assignment")
                ],
            },
        ),
        migrations.CreateModel(
            name="TrainerSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="users.trainer"
                    ),
                ),
            ],
            options={
                "db_table": "trainer_schedules",
                "ordering": ["day_of_week", "start_time"],
                "constraints": [
                    models.UniqueConstraint(fields=("trainer", "day_of_week"), name="uq_trainer_schedule_day")
                ],
            },
        ),
    ]
