# Generated by Django 6.1 on 2026-09-20 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_features"),
        ("users", "0005_add_email_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("code_hash", models.CharField(max_length=64)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "otp_codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["phone", "created_at"], name="idx_otp_phone_created"),
                    models.Index(fields=["ip", "created_at"], name="idx_otp_ip_created"),
                ],
            },
        ),
    ]
