# Generated by Django 6.1 on 2026-08-23 05:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_yearly", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_branches", models.PositiveIntegerField()),
                ("max_customers", models.PositiveIntegerField()),
                ("max_trainers", models.PositiveIntegerField()),
                ("features", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="VendorRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("business_name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(max_length=200)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "selected_plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "email_verification_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("email_verified", "Email Verified"),
                            ("plan_selected", "Plan Selected"),
                            ("provisioned", "Provisioned"),
                            ("onboarded", "Onboarded"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "provisioned_tenant_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vendor_registrations",
                "ordering": ["-created_at"],
            },
        ),
    ]
