# Generated by Django 6.1 on 2026-09-19 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_tenant_is_wati_enabled_tenant_wati_api_key_and_more"),
        ("users", "0005_add_email_verification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpersonationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonations_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        help_text="The short-lived token issued for this session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impersonation_logs",
                        to="users.authtoken",
                    ),
                ),
            ],
            options={
                "db_table": "impersonation_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
