# Generated by Django 6.1 on 2026-08-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(max_length=220)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "exercise_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("muscle_groups", models.JSONField(blank=True, default=list)),
                ("equipment_needed", models.JSONField(blank=True, default=list)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("instructions", models.JSONField(blank=True, default=list)),
                ("media_url", models.URLField(blank=True, null=True)),
                ("tips", models.TextField(blank=True)),
                ("contraindications", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="exercises.exercisecategory",
                    ),
                ),
            ],
            options={
                "db_table": "exercises",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="exercisecategory",
            constraint=models.UniqueConstraint(fields=("tenant", "slug"), name="uq_exercise_category_tenant_slug"),
        ),
    ]
