# Generated by Django 6.1 on 2026-08-23 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchtrainerassignment",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_assignments",
                to="users.trainer",
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_branch_tenant_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="branchamenity",
            constraint=models.UniqueConstraint(
                fields=("branch", "name"), name="uq_amenity_branch_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="branchtrainerassignment",
            constraint=models.UniqueConstraint(
                fields=("branch", "trainer"), name="uq_branch_trainer"
            ),
        ),
    ]
