# Generated by Django 6.1 on 2026-08-24 14:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("analysis_date", models.DateField(default=django.utils.timezone.localdate)),
                ("height_cm", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=5)),
                ("bmi", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("body_fat_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("muscle_mass_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("posture_score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("notes", models.TextField(blank=True)),
                ("photo_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "body_analyses",
                "ordering": ["-analysis_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BodyPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "photo_type",
                    models.CharField(
                        choices=[("front", "Front"), ("side", "Side"), ("back", "Back")], default="front", max_length=10
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("analysis_result", models.JSONField(blank=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="body_analysis.bodyanalysis",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "body_photos",
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BodyProgressLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("weight", "Weight"),
                            ("bmi", "BMI"),
                            ("body_fat", "Body Fat"),
                            ("muscle", "Muscle"),
                            ("waist", "Waist"),
                            ("chest", "Chest"),
                            ("arm", "Arm"),
                            ("thigh", "Thigh"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=7)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_progress_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "body_progress_logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bodyanalysis",
            index=models.Index(fields=["tenant", "user", "analysis_date"], name="idx_body_analysis_user_date"),
        ),
        migrations.AddIndex(
            model_name="bodyprogresslog",
            index=models.Index(fields=["tenant", "user", "date"], name="idx_body_progress_user_date"),
        ),
    ]
