# Generated by Django 6.1 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_extensions"),
        ("tenants", "0002_tenant_is_wati_enabled_tenant_wati_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymeasurement",
            name="biceps_cm",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="bodymeasurement",
            name="bmi",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="bodymeasurement",
            name="body_fat_percentage",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="bodymeasurement",
            name="height_cm",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="bodymeasurement",
            name="neck_cm",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="bodymeasurement",
            name="thighs_cm",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="fitnessgoal",
            name="current_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="fitnessgoal",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("achieved", "Achieved"), ("abandoned", "Abandoned")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fitnessgoal",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fitnessgoal",
            name="target_unit",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="healthprofile",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="healthprofile",
            name="current_injuries",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="healthprofile",
            name="dietary_restrictions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="healthprofile",
            name="food_allergies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="healthprofile",
            name="past_injuries",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="fitnessgoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("lose_weight", "Lose Weight"),
                    ("build_muscle", "Build Muscle"),
                    ("endurance", "Endurance"),
                    ("flexibility", "Flexibility"),
                    ("general_fitness", "General Fitness"),
                    ("sport_specific", "Sport Specific"),
                    ("other", "Other"),
                ],
                default="general_fitness",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="fitnessgoal",
            name="target_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name="fitnessgoal",
            index=models.Index(fields=["tenant", "status"], name="idx_fitnessgoal_status"),
        ),
    ]
