# Generated by Django 6.1 on 2026-08-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_bodymeasurement_biceps_cm_bodymeasurement_bmi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                default="prefer_not_to_say",
                max_length=20,
                null=True,
            ),
        ),
    ]
