# Generated by Django 6.1 on 2026-08-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_allow_null_gender_emergency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                default="prefer_not_to_say",
                max_length=20,
            ),
        ),
    ]
