# Generated by Django 6.1 on 2026-08-24 16:03

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_wati_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="wati_api_key",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="tenant",
            name="wati_endpoint",
            field=models.URLField(blank=True),
        ),
    ]
