# Generated by Django 6.1 on 2026-09-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_is_wati_enabled_tenant_wati_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="features",
            field=models.JSONField(
                blank=True, default=dict, help_text="Feature toggles for this gym, e.g. {marketplace: true}"
            ),
        ),
    ]
