# Generated by Django 6.1 on 2026-08-24 11:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_extensions"),
        ("exercises", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        blank=True, help_text="Alternative to day_of_week: 1-7 for the day within the week.", null=True
                    ),
                ),
                (
                    "focus",
                    models.CharField(blank=True, help_text="e.g. 'Push Day', 'Leg Day', 'Full Body'.", max_length=200),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "workout_days",
                "ordering": ["workout_plan", "day_number", "day_of_week"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sets", models.PositiveIntegerField(default=3)),
                ("reps", models.CharField(default="8-12", help_text="e.g. '8-12' or '10'.", max_length=50)),
                ("rest_seconds", models.PositiveIntegerField(default=60)),
                ("tempo", models.CharField(blank=True, help_text="e.g. '3-1-2'.", max_length=50, null=True)),
                (
                    "rpe",
                    models.PositiveIntegerField(
                        blank=True, help_text="Rate of perceived exertion on a 1-10 scale.", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "alternate_exercise",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional alternate exercise for supersets.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alternate_workout_exercises",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workout_exercises",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exercises", to="workouts.workoutday"
                    ),
                ),
            ],
            options={
                "db_table": "workout_exercises",
                "ordering": ["workout_day", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_completed", models.DateField(default=django.utils.timezone.localdate)),
                ("set_number", models.PositiveIntegerField(default=1)),
                ("actual_reps", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_weight", models.FloatField(blank=True, null=True)),
                ("actual_rest_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="workouts.workoutday"
                    ),
                ),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="workouts.workoutexercise"
                    ),
                ),
            ],
            options={
                "db_table": "workout_logs",
                "ordering": ["-date_completed", "set_number"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("hypertrophy", "Hypertrophy"),
                            ("endurance", "Endurance"),
                            ("weight_loss", "Weight Loss"),
                            ("general_fitness", "General Fitness"),
                        ],
                        default="general_fitness",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("duration_weeks", models.PositiveIntegerField(default=4)),
                (
                    "is_template",
                    models.BooleanField(
                        default=False, help_text="Template plans can be duplicated to create new plans."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workout_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "workout_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="workoutday",
            name="workout_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="days", to="workouts.workoutplan"
            ),
        ),
        migrations.CreateModel(
            name="WorkoutAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(default=django.utils.timezone.localdate)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workout_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_assignments",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="workouts.workoutplan",
                    ),
                ),
            ],
            options={
                "db_table": "workout_assignments",
                "ordering": ["-created_at"],
            },
        ),
    ]
