# Generated by Django 6.1 on 2026-08-24 15:57

import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_extensions"),
        ("memberships", "0001_initial"),
        ("payments", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("refund_id", models.CharField(blank=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("processed", "Processed"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RazorpayConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_key", apps.core.fields.EncryptedCharField(blank=True, max_length=255)),
                ("api_secret", apps.core.fields.EncryptedCharField(blank=True, max_length=255)),
                ("webhook_secret", apps.core.fields.EncryptedCharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "razorpay_configs",
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["tenant", "razorpay_order_id"], name="idx_payment_order_id"),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="payments.payment"
            ),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="tenant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"),
        ),
        migrations.AddField(
            model_name="razorpayconfig",
            name="tenant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(fields=["tenant", "payment"], name="idx_refund_tenant_payment"),
        ),
    ]
