# Generated by Django 6.1 on 2026-09-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentrefund_razorpayconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("online", "Online"),
                    ("upi", "UPI"),
                    ("bank_transfer", "Bank Transfer"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
