"""AI Nutrition Assistant models.

Provides AI-generated weekly meal plans, shopping lists and daily macro logs.
All tenant-scoped data inherits ``TenantModelMixin`` for multi-tenant isolation.
"""

import uuid

from django.db import models
from django.utils import timezone

from apps.diet.models import FoodItem
from apps.tenants.models import TenantModelMixin
from apps.users.models import User


class AIMealPlan(TenantModelMixin):
    """A tenant-scoped weekly meal plan generated by the AI assistant."""

    class Status(models.TextChoices):
        """Lifecycle states of a meal plan."""

        ACTIVE = "active", "Active"
        ARCHIVED = "archived", "Archived"

    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        unique=True,
        db_index=True,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="ai_meal_plans",
    )
    name = models.CharField(max_length=200)
    target_calories = models.PositiveIntegerField(default=0)
    target_protein_g = models.FloatField(default=0)
    target_carbs_g = models.FloatField(default=0)
    target_fat_g = models.FloatField(default=0)
    cuisine_preference = models.CharField(max_length=50, blank=True)
    dietary_restrictions = models.JSONField(
        default=list,
        blank=True,
        help_text="JSON array of dietary restrictions, e.g. ['vegetarian', 'no-gluten'].",
    )
    start_date = models.DateField(default=timezone.localdate)
    end_date = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.ACTIVE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        """AIMealPlan model metadata."""

        db_table = "ai_meal_plans"
        ordering = ["-created_at"]

    def __str__(self) -> str:
        """Return a human-readable meal plan label."""
        return f"{self.name} ({self.user.email})"


class AIMealPlanItem(TenantModelMixin):
    """A single meal entry within an AI meal plan for a given day."""

    class MealType(models.TextChoices):
        """Meal slots within a day."""

        BREAKFAST = "breakfast", "Breakfast"
        LUNCH = "lunch", "Lunch"
        SNACK = "snack", "Snack"
        DINNER = "dinner", "Dinner"

    meal_plan = models.ForeignKey(
        AIMealPlan,
        on_delete=models.CASCADE,
        related_name="items",
    )
    day_of_week = models.PositiveSmallIntegerField(
        choices=[(i, str(i)) for i in range(7)],
        help_text="0 = Monday ... 6 = Sunday.",
    )
    meal_type = models.CharField(
        max_length=20,
        choices=MealType.choices,
        default=MealType.BREAKFAST,
    )
    food_item = models.ForeignKey(
        FoodItem,
        on_delete=models.PROTECT,
        related_name="ai_meal_plan_items",
    )
    servings = models.FloatField(
        default=1.0,
        help_text="Multiplier of the food item's serving size.",
    )
    calories = models.FloatField(
        default=0,
        help_text="Auto-calculated = food_item.calories × servings.",
    )
    protein_g = models.FloatField(
        default=0,
        help_text="Auto-calculated = food_item.protein × servings.",
    )
    carbs_g = models.FloatField(
        default=0,
        help_text="Auto-calculated = food_item.carbs × servings.",
    )
    fat_g = models.FloatField(
        default=0,
        help_text="Auto-calculated = food_item.fat × servings.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        """AIMealPlanItem model metadata."""

        db_table = "ai_meal_plan_items"
        ordering = ["meal_plan", "day_of_week", "meal_type", "id"]

    def __str__(self) -> str:
        """Return a human-readable meal item label."""
        return f"Day {self.day_of_week} {self.meal_type}: {self.food_item.name} × {self.servings}"

    def save(self, *args: object, **kwargs: object) -> None:
        """Persist the item, auto-calculating nutrition from the food item."""
        food = self.food_item
        self.calories = round(food.calories * self.servings, 2)
        self.protein_g = round(food.protein * self.servings, 2)
        self.carbs_g = round(food.carbs * self.servings, 2)
        self.fat_g = round(food.fat * self.servings, 2)
        super().save(*args, **kwargs)


class ShoppingList(TenantModelMixin):
    """A tenant-scoped shopping list generated from an AI meal plan."""

    class Status(models.TextChoices):
        """Lifecycle states of a shopping list."""

        ACTIVE = "active", "Active"
        COMPLETED = "completed", "Completed"

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="ai_shopping_lists",
    )
    meal_plan = models.ForeignKey(
        AIMealPlan,
        on_delete=models.CASCADE,
        related_name="shopping_lists",
    )
    name = models.CharField(max_length=200)
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.ACTIVE,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "ai_shopping_lists"
        ordering = ["-created_at"]

    def __str__(self) -> str:
        """Return a human-readable shopping list label."""
        return f"{self.name} ({self.status})"


class ShoppingListItem(TenantModelMixin):
    """A single grocery item within a shopping list."""

    shopping_list = models.ForeignKey(
        ShoppingList,
        on_delete=models.CASCADE,
        related_name="items",
    )
    food_item = models.ForeignKey(
        FoodItem,
        on_delete=models.PROTECT,
        related_name="ai_shopping_list_items",
    )
    quantity = models.FloatField(default=1.0)
    unit = models.CharField(max_length=50, default="serving")
    is_purchased = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "ai_shopping_list_items"
        ordering = ["shopping_list", "id"]

    def __str__(self) -> str:
        """Return a human-readable shopping list item label."""
        return f"{self.food_item.name} × {self.quantity} {self.unit}"


class MacroLog(TenantModelMixin):
    """A tenant-scoped daily record of consumed macros and water intake."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="ai_macro_logs",
    )
    date = models.DateField(default=timezone.localdate)
    calories_consumed = models.FloatField(default=0)
    protein_consumed_g = models.FloatField(default=0)
    carbs_consumed_g = models.FloatField(default=0)
    fat_consumed_g = models.FloatField(default=0)
    water_intake_ml = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "ai_macro_logs"
        ordering = ["-date", "-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["tenant", "user", "date"],
                name="uq_ai_macro_log_tenant_user_date",
            ),
        ]

    def __str__(self) -> str:
        """Return a human-readable macro log label."""
        return f"{self.user.email} — {self.date}"
