# Generated by Django 6.1 on 2026-08-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="legal_name",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="settings",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="status",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="uuid",
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
