# Generated by Django 6.1 on 2026-09-11 00:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0002_initial"),
        ("customers", "0005_sync_emergency_nullable"),
        ("tenants", "0002_tenant_is_wati_enabled_tenant_wati_api_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "vendor",
                    models.CharField(
                        choices=[
                            ("hikvision", "Hikvision"),
                            ("zkteco", "ZKTeco"),
                            ("essl", "eSSL"),
                            ("matrix", "Matrix"),
                            ("supervision", "Supervision"),
                            ("generic", "Generic HTTP/MQTT"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model", models.CharField(max_length=128)),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Device serial / MAC / IMEI",
                        max_length=64,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable name, e.g. 'Main Entrance'", max_length=128)),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("webhook", "Webhook Push (device calls us)"),
                            ("agent", "Agent Pull (our agent polls device)"),
                            ("cloud_api", "Cloud Sync (vendor cloud API)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("api_endpoint", models.URLField(blank=True, help_text="Device webhook or cloud API URL")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, help_text="Device API key / secret (encrypted at rest)", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_devices",
                        to="branches.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["branch__name", "name"],
                "unique_together": {("branch", "serial_number")},
            },
        ),
        migrations.CreateModel(
            name="AccessOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allow_access", models.BooleanField(help_text="True = grant access, False = deny access")),
                ("reason", models.CharField(max_length=32)),
                ("reason_notes", models.TextField(blank=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Auto-revert after this time; null = permanent", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_overrides_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_overrides",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="access.biometricdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_user_id", models.CharField(max_length=64)),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("fingerprint", "Fingerprint"),
                            ("face", "Face Recognition"),
                            ("card", "RFID Card"),
                            ("pin", "PIN Code"),
                            ("qr", "QR Code"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("entry", "Entry"),
                            ("exit", "Exit"),
                            ("denied", "Access Denied"),
                            ("error", "Device Error"),
                        ],
                        max_length=16,
                    ),
                ),
                ("event_timestamp", models.DateTimeField()),
                ("raw_payload", models.JSONField(default=dict, help_text="Raw device payload for debugging")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="access.biometricdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BiometricCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("fingerprint", "Fingerprint"),
                            ("face", "Face Recognition"),
                            ("card", "RFID Card"),
                            ("pin", "PIN Code"),
                            ("qr", "QR Code"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "device_user_id",
                    models.CharField(
                        help_text="User ID assigned on the device (e.g. device index number)", max_length=64
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_credentials",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="access.biometricdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["device__name", "device_user_id"],
                "unique_together": {("device", "device_user_id")},
            },
        ),
    ]
