# Generated by Django 6.1 on 2026-09-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biometricdevice",
            name="vendor",
            field=models.CharField(
                choices=[
                    ("hikvision", "Hikvision"),
                    ("zkteco", "ZKTeco"),
                    ("essl", "eSSL"),
                    ("matrix", "Matrix"),
                    ("suprema", "Suprema"),
                    ("anviz", "Anviz"),
                    ("dahua", "Dahua"),
                    ("realtime", "Realtime"),
                    ("mantra", "Mantra"),
                    ("timewatch", "TimeWatch"),
                    ("generic", "Generic HTTP/MQTT"),
                ],
                max_length=32,
            ),
        ),
    ]
