# Generated by Django 6.1 on 2026-09-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_alter_biometricdevice_vendor"),
        ("tenants", "0002_tenant_is_wati_enabled_tenant_wati_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCommandQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("command", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_commands",
                        to="access.biometricdevice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
