# Generated by Django 6.1 on 2026-09-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0003_devicecommandqueue"),
        ("customers", "0005_sync_emergency_nullable"),
        ("tenants", "0002_tenant_is_wati_enabled_tenant_wati_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessDecisionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allowed", models.BooleanField(help_text="True = entry granted, False = denied.")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("override", "Owner Override"),
                            ("plan_active", "Active Plan"),
                            ("plan_expired", "Plan Expired"),
                            ("no_membership", "No Membership"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_decisions",
                        to="customers.customer",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_logs",
                        to="access.biometricdevice",
                    ),
                ),
                (
                    "override",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the decision came from an owner override.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decision_logs",
                        to="access.accessoverride",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
    ]
